# This setting acts as a security precaution by postponing the installation of newly published package versions. Delaying installations helps reduce the risk of compromised packages,
# as most malicious releases are typically identified and removed from the registry within an hour.
minimumReleaseAge: 2880 # 2 days (1 day by default)
allowBuilds:
  '@sveltejs/kit': false
  core-js: false
  esbuild: false
  lefthook: false
  svelte-preprocess: false
  unrs-resolver: false
